import React from "react";
import type { Metadata } from "next";
import "./global.css";
import MainLayout from "../layouts/MainLayout";

export const metadata: Metadata = {
  title: "Mobile App Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
