import React from "react";
import type { Metadata } from "next";
import MainLayout from "../layouts/MainLayout";
import "../global.css";
import { ConfigProvider } from "antd";

export const metadata: Metadata = {
  title: "Mobile App Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body>
        <ConfigProvider
        theme={{
          token: {
            fontFamily: 'Tektur'
          },
        }}
        >
          <MainLayout>{children}</MainLayout>
        </ConfigProvider>
      </body>
    </html>
  );
}
